numero = int(input("digite o número que você deseja saber a tabuada:"))

print("{} x 1 = ".format(numero), numero*1)
print("{} x 2 = ".format(numero), numero*2)
print("{} x 2 = ".format(numero), numero*3)
print("{} x 2 = ".format(numero), numero*4)
print("{} x 2 = ".format(numero), numero*5)
print("{} x 2 = ".format(numero), numero*6)
print("{} x 2 = ".format(numero), numero*7)
print("{} x 2 = ".format(numero), numero*8)
print("{} x 2 = ".format(numero), numero*9)
print("{} x 2 = ".format(numero), numero*10)